---
- name: reload systemd_exporter
  systemd:
    name: systemd_exporter
    state: reloaded
  become: true
  tags: systemd_exporter

- name: restart systemd_exporter
  systemd:
    daemon_reload: true
    name: systemd_exporter
    state: restarted
  become: true
  tags: systemd_exporter